import { describe, expect, test } from "bun:test";
import Game from "../src/game";

describe('Game', () => {
    test('should play until player death', () => {
        const game = new Game()
        game.init()

        game.play('NNNWWWWWBBBWWSSSSSSSSSSSSSSSSEEWE')

        expect(game.state.entities["player"]).toBeUndefined()
        expect(game.state.actionLog.join('')).toBe('NNNWWWWWBBBWWSSSSSSSSSSSSSSSSEEWE')
    })

    test('should play through the manual', () => {
        const game = new Game()
        game.init()
        expect(Object.keys(game.state.entities).length).toBe(29)

        game.play('EEEEEEEEESSSSSEEEESSEENEENESWWSAAWSSSSESSEEEEEEEEEEEEEEENWWNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWSWSSSSSSSSSSSSSSSSENEEEEEEEESNWWWWWWWWSSSSSSSEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEENNN')

        expect(Object.keys(game.state.entities).length).toBe(28)
        expect(game.state.entities["player"]).toBeDefined()
    })

    test('should beat the game', () => {
        const game = new Game()
        game.init()
        expect(Object.keys(game.state.entities).length).toBe(29)

        game.play('"WWWNEEEEEEEEEEEEEENEEEEEEESEEEEESSSSSSEEEEEEEEENNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWSSWSSSSSSEWNNNNMMNWWWWWWWWWWWSSSSSWSWWEESSSSSSSSSSSSSSSSSSSSSSSSSWWWWWWWWWWWWWSBSWWWNNNENNNNWWWWWWWWWWWWSSSSSSSSSSWWWSWWNNNMNNNNNNMNNEMEEEESMSENNSSSSSSWWWWWNNNNNEEESSWWNESSWSEEENNWSEEENNNNNNNENNNNEEEEEEEMEENNNNNNNNNNNNNNNNNNSSSSSSEEEEEESEEEMEESEAAAAAAAAAAAAAAAAAAAAAAAAAAAAASSSSSSESEEEEEEEEENNWWWWEEEESSWWWWWWWWWWWNNNNNNNWNWWWWNWWWWWWWWNNNNNNWWWWWWWWWWWWWWWWWSESSEESSEESSSWWSSESSWWWWNNNNNWSWNWNNAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAASSEESSSEENNNNNNNNNNNNWNWESEEESSSSSSSSSSSSSEWWENNNNNWWNNNNNNNNNWNWWWWWWWWSSSEEEEEEEEEEEEENNNNNNNWSSSSSSSSSSSSSSSSSSSSSSSSSSENNNNNNNNNWNNNENNNNNNENEEEEWWWWWWWWWWWWWWWWSWAAWSSSSSSSEEEEEEEEEESSSSSEEEEEEEWSSWWWWNNNNWWNNAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAASSEESSSEEEEEEEEMESSWWWWWWNNNNWNWNNAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAASSSEESSEENNNNNEEEENNNNNNEEEEEEEEEEEEEEEEEEWWSSSSSSSEEEMEESBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBNNWSWWWNNNNEENNNNNNNEEEEEEEEEEEESSWWWWWWSSSSSEEEESAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANWWWWNNNNEEEENNNNNSEEEEESSSSSESSSSSEEEEEEEEEEEEWWWWWWWWNNNNNNNWSSWWSWWSSWSSSSEEEESBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBNWWWWNNNNNNNEEEENNSSSSEEEEEEESESESESESESESESESESESESESWWNWNWNWNWNWNWNWNWNWNWNWNNNWSSSSSWWWW')

        expect(Object.keys(game.state.entities).length).toBe(13)
        expect(game.state.entities["player"]).toBeDefined()
    })
})